lua_shared_dict waf_cache 30m;
lua_shared_dict waf_drop 30m;
lua_shared_dict waf_stats 30m;
lua_shared_dict waf_data 100m;
lua_package_path "D:/waf_nginx/?.lua";
init_by_lua_file  D:/waf_nginx/init.lua;
access_by_lua_file D:/waf_nginx/waf.lua;
